/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbusscreenshotservice -c DBusScreenshotService -l DBusScreenshotService com.deepin.DeepinScreenshot.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusscreenshotservice.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusScreenshotService
 */

DBusScreenshotService::DBusScreenshotService(MainWindow *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusScreenshotService::~DBusScreenshotService()
{
    // destructor
}

void DBusScreenshotService::DelayScreenshot(qlonglong in0)
{
    // handle method call com.deepin.DeepinScreenshot.DelayScreenshot
    parent()->DelayScreenshot(in0);
}

void DBusScreenshotService::FullscreenShot()
{
    // handle method call com.deepin.DeepinScreenshot.FullscreenShot
    parent()->FullscreenShot();
}

void DBusScreenshotService::SavePath(const QString &in0)
{
    // handle method call com.deepin.DeepinScreenshot.SavePath
    parent()->SavePath(in0);
}

