/*
 * Copyright (C) 2017 ~ 2017 Deepin Technology Co., Ltd.
 *
 * Maintainer: Peng Hui<penghui@deepin.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbusscreenshotservice -c DBusScreenshotService -l DBusScreenshotService com.deepin.Screenshot.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusscreenshotservice.h"
#include "screenshot.h"

#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusScreenshotService
 */

DBusScreenshotService::DBusScreenshotService(Screenshot *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusScreenshotService::~DBusScreenshotService()
{
    // destructor
}

void DBusScreenshotService::StartScreenshot() {
    parent()->StartScreenshot();
}

void DBusScreenshotService::DelayScreenshot(qlonglong in0)
{
    // handle method call com.deepin.Screenshot.DelayScreenshot
    parent()->DelayScreenshot(in0);
}

void DBusScreenshotService::NoNotifyScreenshot()
{
    // handle method call com.deepin.Screenshot.NoNotify
    parent()->NoNotifyScreenshot();
}

void DBusScreenshotService::TopWindowScreenshot()
{
    // handle method call com.deepin.Screenshot.TopWindow
    parent()->TopWindowScreenshot();
}

void DBusScreenshotService::FullscreenScreenShot()
{
    // handle method call com.deepin.Screenshot.FullscreenShot
    parent()->FullscreenScreenShot();
}

void DBusScreenshotService::SavePathScreenshot(const QString &in0)
{
    // handle method call com.deepin.Screenshot.SavePath
    parent()->SavePathScreenshot(in0);
}

