/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusSoundEffect -p dbussoundeffect com.deepin.daemon.SoundEffect.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbussoundeffect.h"

/*
 * Implementation of interface class DBusSoundEffect
 */

const QString SOUNDEFFECT_DBUS_NAME = "com.deepin.daemon.SoundEffect";
const QString SOUNDEFFECT_DBUS_PATH = "/com/deepin/daemon/SoundEffect";

DBusSoundEffect::DBusSoundEffect(QObject *parent)
    : QDBusAbstractInterface(SOUNDEFFECT_DBUS_NAME,  SOUNDEFFECT_DBUS_PATH,
                             staticInterfaceName(),  QDBusConnection::sessionBus(), parent)
{
    QDBusConnection::sessionBus().connect(this->service(), this->path(),
    "org.freedesktop.DBus.Properties", "PropertiesChanged","sa{sv}as",
                                          this, SLOT(__propertyChanged__(QDBusMessage)));
}

DBusSoundEffect::~DBusSoundEffect()
{
    QDBusConnection::sessionBus().disconnect(service(), path(),
    "org.freedesktop.DBus.Properties", "PropertiesChanged", "sa{sv}as",
                                             this, SLOT(propertyChanged(QDBusMessage)));
}

