/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusScreenshot -p dbusscreenshot com.deepin.DeepinScreenshot.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusscreenshot.h"

/*
 * Implementation of interface class DBusScreenshot
 */

const QString SCREENSHOT_DBUS_NAME = "com.deepin.DeepinScreenshot";
const QString SCREENSHOT_DBUS_PATH = "/com/deepin/DeepinScreenshot";

DBusScreenshot::DBusScreenshot(QObject* parent)
   : QDBusAbstractInterface(SCREENSHOT_DBUS_NAME, SCREENSHOT_DBUS_PATH,
                             staticInterfaceName(), QDBusConnection::sessionBus(), parent)
 {
    QDBusConnection::sessionBus().connect(this->service(), this->path(),
    "org.freedesktop.DBus.Properties", "PropertiesChanged","sa{sv}as",
                                         this, SLOT(__propertyChanged__(QDBusMessage)));
 }

 DBusScreenshot::~DBusScreenshot()
 {
    QDBusConnection::sessionBus().disconnect(service(), path(),
   "org.freedesktop.DBus.Properties", "PropertiesChanged", "sa{sv}as",
                                            this, SLOT(propertyChanged(QDBusMessage)));
 }


