#!/bin/bash
# -*- coding: utf-8 -*-

# Copyright (C) 2011 Deepin, Inc.
#               2011 Zhang Cheng
# 
# Author:     Zhang Cheng <zhangcheng@linuxdeepin.com>
# Maintainer: Zhang Cheng <zhangcheng@linuxdeepin.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

REALNAME=$(which $0)

## if it is a link, find the original file through recursively readlink
while [[ -L "$REALNAME" ]]; do
    LINKNAME=$(readlink $REALNAME)
    [[ $LINKNAME == /* ]] \
	&& REALNAME=$LINKNAME \
	|| REALNAME="$(dirname $REALNAME)/$LINKNAME"
done

cd $(dirname $REALNAME) && ./deepinScrot.py $@
