#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2015 Deepin Technology Co., Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

import gtk
import sys
import os

image_file = sys.argv[1]

if os.path.exists(image_file):
    pixbuf = gtk.gdk.pixbuf_new_from_file(image_file)
    clipboard = gtk.Clipboard()
    clipboard.set_image(pixbuf)
    clipboard.store()
    sys.exit(0)
else:
    sys.exit(1)
